# Generated by Django 4.2.6 on 2024-01-05 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('url', models.CharField(max_length=400, unique=True)),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(null=True)),
                ('date_published', models.CharField(default='', max_length=255)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='news_thumbs/')),
                ('author_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
