# Generated by Django 4.2.9 on 2024-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='date_published',
            new_name='date_published_text',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='date_published_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
