# Generated by Django 4.2.6 on 2023-12-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='date',
            new_name='date_created',
        ),
    ]
