# Generated by Django 4.2.6 on 2023-12-14 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_rename_date_newsarticle_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to='news_thumbs/'),
        ),
    ]
