# Generated by Django 4.2.9 on 2024-08-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
