# Generated by Django 4.2.9 on 2024-07-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_topic_delete_book_remove_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reply_images/'),
        ),
    ]
