# Generated by Django 4.2.9 on 2024-08-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_category_reply_topic_delete_book_remove_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.topic'),
        ),
    ]
