# Generated by Django 4.2.9 on 2024-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_reply_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
