# Generated by Django 4.2.9 on 2024-07-13 19:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='replies/'),
        ),
        
    ]
