# Generated by Django 4.2.9 on 2024-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_category_reply_parent_reply_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
