# Generated by Django 4.2.9 on 2025-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial_squashed_0005_alter_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(default='', verbose_name='Bericht'),
        ),
    ]
