# Generated by Django 4.2.9 on 2024-08-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_category_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.category', verbose_name='Categorie'),
        ),
    ]
