# Generated by Django 4.2.6 on 2023-12-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
