# Generated by Django 4.2.6 on 2023-12-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_author_id_conversation_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='author',
            new_name='author_id',
        ),
    ]
