# Generated by Django 4.2.6 on 2023-12-20 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_author_conversation_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_text',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='author_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
