# Generated by Django 4.2.9 on 2024-08-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_conversation_remove_saved_conversations_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='author',
            new_name='user',
        ),
        migrations.CreateModel(
            name='GroupedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('user_inputs', models.JSONField()),
                ('bot_responses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
