# Generated by Django 4.2.9 on 2024-08-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_savedconversation_delete_groupedconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='bot_response',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_input',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavedConversation',
        ),
        migrations.AddField(
            model_name='singleuserbot',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_entries', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='singleuserbot',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
