# Generated by Django 4.2.9 on 2024-08-28 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_singleuserbot_remove_conversation_bot_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleuserbot',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
