# Generated by Django 4.2.9 on 2024-08-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_singleuserbot_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleuserbot',
            old_name='conversation',
            new_name='parent',
        ),
    ]
