# Generated by Django 4.2.9 on 2024-08-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_conversation_singleuserbot_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleuserbot',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_entries', to='chat.conversation'),
        ),
    ]
