# Generated by Django 4.2.6 on 2023-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pcode', models.CharField(max_length=6)),
                ('hnumber', models.CharField(max_length=6)),
                ('addition', models.CharField(max_length=4)),
                ('street', models.TextField()),
                ('place', models.TextField()),
                ('EP_label', models.TextField(max_length=5)),
                ('EP_surface', models.PositiveIntegerField(default='')),
                ('BAG_surface', models.PositiveIntegerField(default='')),
                ('buildyear', models.PositiveIntegerField(default='')),
                ('purpose', models.TextField()),
                ('calendaryear', models.PositiveIntegerField(default='2017')),
                ('elektra', models.PositiveIntegerField(default='0')),
                ('gas', models.PositiveIntegerField(default='0')),
                ('weii', models.PositiveBigIntegerField(default='0')),
            ],
        ),
    ]
