# Generated by Django 4.2.6 on 2023-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='weii',
            field=models.TextField(max_length=20),
        ),
    ]
