# Generated by Django 4.2.6 on 2023-12-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_adress_weii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='EP_surface',
        ),
    ]
