# Generated by Django 4.2.9 on 2024-03-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_adress_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='addition',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='adress',
            name='elektra_terug',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
    ]
