# Generated by Django 4.2.6 on 2023-12-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_adress_ep_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='elektra_terug',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
