# Generated by Django 4.2.9 on 2025-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_projectmollier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmollier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
